/* This file was generated by gen.py on 2025-11-20 11:12:08 */
module small_div (
    input logic clk,
    input logic rstn,

    input logic      small_div_valid,
    input idu1_out_t div_ctrl,

    output logic [     XLEN-1:0] instr_tag_out,
    output logic [INSTR_LEN-1:0] instr_out,

    output logic [               XLEN-1:0] div_wb_data,
    output logic [REG_FILE_ADDR_WIDTH-1:0] div_wb_rd_addr,
    output logic                           div_wb_rd_wr_en
);

  logic [3:0] a_ff, b_ff;
  logic [3:0] a, b;

  logic [3:0] q, r;

  logic [REG_FILE_ADDR_WIDTH-1:0] div_wb_rd_addr_i;
  logic                           div_wb_rd_wr_en_i;
  logic                           out_div;

  assign a = div_ctrl.rs1_data[3:0];
  assign b = div_ctrl.imm_valid ? div_ctrl.imm[3:0] : div_ctrl.rs2_data[3:0];

  assign div_wb_data[XLEN-1:0] = out_div ? {{(XLEN-4){1'b0}}, q[3:0]} : ((b_ff[3:0] == 0) ? {{{XLEN-4}{1'b0}},a_ff} : {{(XLEN-4){1'b0}}, r[3:0]});

  assign div_wb_rd_addr_i = div_ctrl.rd_addr;
  assign div_wb_rd_wr_en_i = div_ctrl.rd & div_ctrl.legal & (div_ctrl.divu | div_ctrl.remu) & ~div_ctrl.nop & small_div_valid;

  register_sync_rstn #(
      .WIDTH($bits({div_wb_rd_addr_i, div_wb_rd_wr_en_i}))
  ) div_wb_data_ff (
      .clk (clk),
      .rstn(rstn),
      .din ({div_wb_rd_addr_i, div_wb_rd_wr_en_i}),
      .dout({div_wb_rd_addr, div_wb_rd_wr_en})
  );


  register_sync_rstn #(
      .WIDTH(1)
  ) div_ff (
      .clk (clk),
      .rstn(rstn),
      .din (div_ctrl.divu),
      .dout(out_div)
  );

  register_sync_rstn #(
      .WIDTH(XLEN + INSTR_LEN)
  ) instr_tag_ff (
      .clk (clk),
      .rstn(rstn),
      .din ({div_ctrl.instr_tag, div_ctrl.instr}),
      .dout({instr_tag_out, instr_out})
  );

  register_sync_rstn #(
      .WIDTH(4)
  ) a_div_ff (
      .clk (clk),
      .rstn(rstn),
      .din (a & {4{div_wb_rd_wr_en_i}}),
      .dout(a_ff)
  );
  register_sync_rstn #(
      .WIDTH(4)
  ) b_div_ff (
      .clk (clk),
      .rstn(rstn),
      .din (b & {4{div_wb_rd_wr_en_i}}),
      .dout(b_ff)
  );


  always_comb begin
    q[3] = (a_ff[3] & ~b_ff[3] & ~b_ff[2] & ~b_ff[1] & b_ff[0]);

    q[2] = (a_ff[2]&~b_ff[3]&~b_ff[2]&~b_ff[1]&b_ff[0]) |
	 (a_ff[3]&~b_ff[3]&~b_ff[2]&b_ff[1]&~b_ff[0]) |
	 (    a_ff[3]&a_ff[2]&~b_ff[3]&~b_ff[2]&b_ff[0]);

    q[1] = (a_ff[3]&a_ff[2]&~b_ff[3]&b_ff[2]&~b_ff[1]) |
	 (~a_ff[3]&a_ff[2]&a_ff[1]&~b_ff[3]&~b_ff[2]&b_ff[0]) |
	 (    a_ff[3]&~a_ff[2]&~b_ff[3]&~b_ff[2]&b_ff[1]&b_ff[0]) |
	 (a_ff[2]&~b_ff[3]&~b_ff[2]&b_ff[1]&~b_ff[0]) |
	 (    a_ff[1]&~b_ff[3]&~b_ff[2]&~b_ff[1]&b_ff[0]) |
	 (a_ff[3]&~b_ff[3]&b_ff[2]&~b_ff[1]&~b_ff[0]) |
	 (a_ff[3]    &a_ff[2]&~b_ff[3]&b_ff[1]&~b_ff[0]) |
	 (a_ff[3]&a_ff[1]&~b_ff[3]&~b_ff[1]&b_ff[0]) |
	 (a_ff[3]&a_ff[2]    &a_ff[1]&~b_ff[3]&b_ff[2]);

    q[0] = (~a_ff[3]&a_ff[2]&~a_ff[1]&~a_ff[0]&~b_ff[3]&~b_ff[2]&b_ff[1]&b_ff[0]) |
	 (~a_ff[3]&a_ff[2]&a_ff[1]    &~a_ff[0]&~b_ff[3]&b_ff[2]&~b_ff[1]&b_ff[0]) |
	 (~a_ff[3]&a_ff[2]&~a_ff[1]&a_ff[0]&~b_ff[3]&~b_ff[2]    &b_ff[1]&b_ff[0]) |
	 (a_ff[3]&~a_ff[2]&~a_ff[1]&a_ff[0]&~b_ff[3]&b_ff[2]&~b_ff[1]&b_ff[0]) |
	 (a_ff[3]    &~a_ff[2]&~a_ff[1]&~b_ff[3]&b_ff[2]&b_ff[1]&~b_ff[0]) |
	 (a_ff[3]&~a_ff[2]&~a_ff[1]&~a_ff[0]&~b_ff[3]    &b_ff[2]&b_ff[0]) |
	 (a_ff[3]&a_ff[2]&~a_ff[1]&b_ff[3]&~b_ff[2]&b_ff[1]&~b_ff[0]) |
	 (a_ff[3]&~a_ff[2]    &a_ff[1]&~b_ff[3]&b_ff[2]&b_ff[1]&~b_ff[0]) |
	 (a_ff[3]&a_ff[1]&~a_ff[0]&b_ff[3]&~b_ff[2]&~b_ff[1]&b_ff[0]) |
	 (    a_ff[3]&~a_ff[2]&a_ff[1]&~a_ff[0]&~b_ff[3]&b_ff[1]&b_ff[0]) |
	 (a_ff[3]&a_ff[2]&~a_ff[1]&a_ff[0]&b_ff[3]    &~b_ff[2]&b_ff[1]) |
	 (a_ff[3]&~a_ff[2]&a_ff[1]&a_ff[0]&~b_ff[3]&b_ff[2]&b_ff[1]) |
	 (a_ff[3]&a_ff[2]    &a_ff[1]&~a_ff[0]&b_ff[3]&~b_ff[1]&b_ff[0]) |
	 (a_ff[2]&a_ff[1]&a_ff[0]&~b_ff[3]&~b_ff[1]&b_ff[0]) |
	 (    ~a_ff[3]&a_ff[2]&a_ff[1]&~b_ff[3]&b_ff[1]&~b_ff[0]) |
	 (a_ff[3]&~a_ff[1]&a_ff[0]&~b_ff[3]&b_ff[2]&b_ff[1]    &b_ff[0]) |
	 (~a_ff[3]&a_ff[2]&a_ff[0]&~b_ff[3]&~b_ff[1]&b_ff[0]) |
	 (~a_ff[2]&a_ff[1]&a_ff[0]&~b_ff[3]    &~b_ff[2]&b_ff[0]) |
	 (a_ff[3]&a_ff[2]&~a_ff[1]&~b_ff[3]&b_ff[2]&b_ff[1]&b_ff[0]) |
	 (~a_ff[3]&a_ff[2]    &a_ff[1]&a_ff[0]&~b_ff[3]&b_ff[2]) |
	 (a_ff[3]&~a_ff[2]&a_ff[0]&~b_ff[3]&~b_ff[2]&b_ff[0]) |
	 (a_ff[3]    &a_ff[2]&~a_ff[0]&b_ff[3]&~b_ff[2]&b_ff[0]) |
	 (a_ff[1]&~b_ff[3]&~b_ff[2]&b_ff[1]&~b_ff[0]) |
	 (a_ff[3]    &b_ff[3]&~b_ff[2]&~b_ff[1]&~b_ff[0]) |
	 (a_ff[2]&~b_ff[3]&b_ff[2]&~b_ff[1]&~b_ff[0]) |
	 (a_ff[0]&~b_ff[3]    &~b_ff[2]&~b_ff[1]&b_ff[0]) |
	 (a_ff[3]&a_ff[1]&~b_ff[2]&b_ff[1]&~b_ff[0]) |
	 (a_ff[3]&a_ff[2]&b_ff[2]    &~b_ff[1]&~b_ff[0]) |
	 (a_ff[3]&a_ff[2]&a_ff[1]&b_ff[3]&~b_ff[0]) |
	 (a_ff[3]&a_ff[0]&~b_ff[2]&~b_ff[1]    &b_ff[0]) |
	 (a_ff[3]&a_ff[2]&a_ff[0]&b_ff[3]&~b_ff[1]) |
	 (a_ff[3]&a_ff[1]&a_ff[0]&~b_ff[2]&b_ff[0]) |
	 (    a_ff[3]&a_ff[2]&a_ff[1]&a_ff[0]&b_ff[3]);

    r[3] = (a_ff[3]&a_ff[2]&a_ff[1]&~a_ff[0]&b_ff[3]&b_ff[2]&b_ff[1]&b_ff[0]) |
	 (a_ff[3]&~a_ff[2]&a_ff[1]&~a_ff[0]    &b_ff[3]&b_ff[1]&b_ff[0]) |
	 (a_ff[3]&a_ff[2]&~a_ff[1]&~a_ff[0]&b_ff[3]&b_ff[2]&b_ff[0]) |
	 (a_ff[3]    &~a_ff[2]&~a_ff[1]&~a_ff[0]&b_ff[3]&b_ff[0]) |
	 (a_ff[3]&a_ff[2]&~a_ff[1]&b_ff[3]&b_ff[2]&b_ff[1]) |
	 (    a_ff[3]&~a_ff[2]&~a_ff[1]&b_ff[3]&b_ff[1]) |
	 (a_ff[3]&~a_ff[2]&b_ff[3]&b_ff[2]);

    r[2] = (a_ff[3]&a_ff[2]&a_ff[1]&~a_ff[0]&~b_ff[3]&b_ff[2]&~b_ff[1]&b_ff[0]) |
	 (a_ff[3]&~a_ff[2]&~a_ff[1]    &a_ff[0]&~b_ff[3]&b_ff[2]&~b_ff[1]&b_ff[0]) |
	 (a_ff[3]&a_ff[2]&a_ff[1]&~a_ff[0]&b_ff[3]&b_ff[2]&b_ff[1]    &b_ff[0]) |
	 (~a_ff[3]&a_ff[2]&a_ff[1]&~a_ff[0]&b_ff[2]&b_ff[1]&b_ff[0]) |
	 (a_ff[3]&a_ff[2]&~a_ff[1]    &~a_ff[0]&b_ff[3]&b_ff[2]&b_ff[0]) |
	 (~a_ff[3]&a_ff[2]&~a_ff[1]&~a_ff[0]&b_ff[2]&b_ff[0]) |
	 (a_ff[3]    &~a_ff[2]&a_ff[1]&~b_ff[3]&b_ff[2]&b_ff[1]&~b_ff[0]) |
	 (a_ff[3]&~a_ff[2]&a_ff[1]&a_ff[0]&~b_ff[3]&b_ff[2]    &b_ff[1]) |
	 (a_ff[2]&b_ff[3]&~b_ff[2]&~b_ff[1]&~b_ff[0]) |
	 (a_ff[3]&a_ff[2]&~a_ff[1]&~b_ff[3]&b_ff[2]    &b_ff[1]&b_ff[0]) |
	 (a_ff[2]&a_ff[1]&b_ff[3]&~b_ff[2]&~b_ff[0]) |
	 (a_ff[2]&a_ff[0]&b_ff[3]&~b_ff[2]    &~b_ff[1]) |
	 (a_ff[2]&a_ff[1]&b_ff[3]&~b_ff[2]&~b_ff[1]) |
	 (a_ff[3]&a_ff[2]&~a_ff[1]&b_ff[3]&b_ff[2]    &b_ff[1]) |
	 (a_ff[2]&a_ff[1]&a_ff[0]&b_ff[3]&~b_ff[2]) |
	 (~a_ff[3]&a_ff[2]&~a_ff[1]&b_ff[2]&b_ff[1]) |
	 (    ~a_ff[3]&a_ff[2]&b_ff[3]);

    r[1] = (a_ff[3]&~a_ff[2]&~a_ff[1]&~a_ff[0]&~b_ff[3]&~b_ff[2]&b_ff[1]&b_ff[0]) |
	 (a_ff[3]&a_ff[2]&~a_ff[1]    &~a_ff[0]&b_ff[3]&~b_ff[2]&~b_ff[1]&b_ff[0]) |
	 (~a_ff[2]&a_ff[1]&~a_ff[0]&b_ff[2]&b_ff[1]&b_ff[0]) |
	 (    ~a_ff[3]&a_ff[2]&~a_ff[1]&a_ff[0]&~b_ff[3]&~b_ff[2]&b_ff[1]&b_ff[0]) |
	 (a_ff[3]&~a_ff[2]&a_ff[1]&a_ff[0]    &~b_ff[3]&~b_ff[2]&b_ff[1]&b_ff[0]) |
	 (a_ff[3]&a_ff[2]&a_ff[1]&~a_ff[0]&b_ff[3]&b_ff[2]&b_ff[1]&b_ff[0]) |
	 (    a_ff[3]&a_ff[2]&~a_ff[1]&a_ff[0]&~b_ff[3]&b_ff[2]&~b_ff[1]&b_ff[0]) |
	 (~a_ff[3]&a_ff[1]&a_ff[0]&b_ff[2]    &~b_ff[1]) |
	 (~a_ff[3]&a_ff[2]&a_ff[1]&~a_ff[0]&b_ff[2]&b_ff[1]&b_ff[0]) |
	 (a_ff[3]&~a_ff[1]&~a_ff[0]    &~b_ff[3]&b_ff[2]&~b_ff[1]&b_ff[0]) |
	 (a_ff[3]&~a_ff[2]&a_ff[1]&~a_ff[0]&b_ff[3]&b_ff[1]&b_ff[0]) |
	 (    ~a_ff[3]&~a_ff[2]&a_ff[1]&~a_ff[0]&b_ff[1]&b_ff[0]) |
	 (a_ff[3]&a_ff[2]&a_ff[1]&~a_ff[0]&~b_ff[2]&b_ff[1]    &b_ff[0]) |
	 (a_ff[3]&~a_ff[2]&~a_ff[1]&~b_ff[3]&b_ff[2]&b_ff[1]&~b_ff[0]) |
	 (a_ff[3]&a_ff[2]&~a_ff[1]    &b_ff[3]&~b_ff[2]&b_ff[1]&~b_ff[0]) |
	 (a_ff[3]&a_ff[2]&~a_ff[1]&a_ff[0]&b_ff[3]&~b_ff[2]&b_ff[1]) |
	 (    a_ff[1]&b_ff[3]&~b_ff[1]&~b_ff[0]) |
	 (a_ff[3]&~a_ff[1]&a_ff[0]&~b_ff[3]&b_ff[2]&b_ff[1]&b_ff[0]) |
	 (    a_ff[3]&a_ff[2]&a_ff[1]&~b_ff[3]&b_ff[2]&~b_ff[0]) |
	 (~a_ff[2]&a_ff[1]&b_ff[3]&b_ff[2]) |
	 (~a_ff[3]    &~a_ff[2]&a_ff[1]&b_ff[2]) |
	 (a_ff[1]&b_ff[2]&~b_ff[1]&~b_ff[0]) |
	 (a_ff[1]&a_ff[0]&b_ff[3]&~b_ff[1]) |
	 (    ~a_ff[3]&a_ff[1]&b_ff[3]);

    r[0] = (~a_ff[3]&a_ff[2]&~a_ff[1]&~a_ff[0]&~b_ff[3]&~b_ff[2]&b_ff[1]&b_ff[0]) |
	 (~a_ff[3]&a_ff[2]&a_ff[1]    &~a_ff[0]&~b_ff[3]&b_ff[2]&~b_ff[1]&b_ff[0]) |
	 (a_ff[3]&~a_ff[1]&~a_ff[0]&~b_ff[3]&b_ff[2]&b_ff[1]    &b_ff[0]) |
	 (a_ff[3]&a_ff[2]&~a_ff[1]&a_ff[0]&~b_ff[3]&b_ff[2]&~b_ff[1]&b_ff[0]) |
	 (~a_ff[3]&a_ff[2]    &a_ff[1]&a_ff[0]&~b_ff[2]&b_ff[1]) |
	 (~a_ff[2]&a_ff[1]&a_ff[0]&b_ff[2]&~b_ff[1]) |
	 (~a_ff[1]&a_ff[0]    &b_ff[3]&b_ff[2]&b_ff[1]) |
	 (a_ff[3]&a_ff[2]&~a_ff[1]&a_ff[0]&~b_ff[3]&~b_ff[2]&b_ff[1]) |
	 (a_ff[3]    &~a_ff[2]&~a_ff[1]&~a_ff[0]&~b_ff[3]&b_ff[2]&b_ff[0]) |
	 (~a_ff[3]&~a_ff[1]&a_ff[0]&b_ff[2]&b_ff[1]) |
	 (    a_ff[3]&a_ff[1]&~a_ff[0]&b_ff[3]&~b_ff[2]&~b_ff[1]&b_ff[0]) |
	 (a_ff[3]&~a_ff[2]&a_ff[1]&~a_ff[0]&~b_ff[3]    &b_ff[1]&b_ff[0]) |
	 (a_ff[3]&a_ff[2]&a_ff[1]&a_ff[0]&~b_ff[3]&b_ff[2]&b_ff[1]) |
	 (~a_ff[2]&~a_ff[1]    &a_ff[0]&b_ff[3]&b_ff[1]) |
	 (a_ff[3]&a_ff[2]&a_ff[1]&~a_ff[0]&b_ff[3]&~b_ff[1]&b_ff[0]) |
	 (a_ff[0]    &b_ff[3]&~b_ff[0]) |
	 (~a_ff[3]&~a_ff[2]&~a_ff[1]&a_ff[0]&b_ff[1]) |
	 (a_ff[3]&a_ff[2]&~a_ff[0]&b_ff[3]    &~b_ff[2]&b_ff[0]) |
	 (~a_ff[2]&a_ff[0]&b_ff[3]&b_ff[2]) |
	 (~a_ff[3]&~a_ff[2]&a_ff[0]&b_ff[2]) |
	 (    ~a_ff[3]&a_ff[0]&b_ff[3]) |
	 (a_ff[0]&b_ff[1]&~b_ff[0]) |
	 (a_ff[0]&b_ff[2]&~b_ff[0]);


  end
endmodule
